version: "3.8"

services:
  postgres:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_DB=my_store
      - POSTGRES_USER=mati
      - POSTGRES_PASSWORD=admin123
    ports:
      - 5432:5432  
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: 'matimanu09@hotmail.com'
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
     - '5050:80'

    depends_on:
      - postgres


